web_app/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, session
from flask_login import login_user, login_required, logout_user
from flask_injector import FlaskInjector
from injector import inject
from werkzeug.security import check_password_hash

from forms.User import RegistrationForm
from services.Auth import AuthService
from services.User import UserService

auth_app = Blueprint('auth_app', __name__, template_folder='templates')

@inject
@auth_app.route('/register', methods=['GET', 'POST'], endpoint="register")
def register(auth_service: AuthService):
    
    if request.method == 'GET':
        return render_template('auth/register.html', form_values=session.get('registration_data'))

    # On submitting registration form:
    req_params = request.form
    form = RegistrationForm(req_params)
    
    if form.validate():
        return auth_service.handle_user_registration(req_params)

    return auth_service.handle_unsuccessful_registration(req_params, form)


@inject
@auth_app.route('/login', methods=['GET', 'POST'], endpoint="login")
def login(auth_service: AuthService, user_service: UserService):
    
    if request.method == 'GET':
        return render_template('auth/login.html')
    
    user = user_service.get_user_by_email(request.form.get('email'))

    if user and check_password_hash(user.password, request.form.get('password')):
        return auth_service.handle_successful_login(user)
    
    return auth_service.handle_unsuccessful_login(user)


@login_required
@auth_app.route("/logout", methods=['GET'], endpoint="logout")
def logout():
    logout_user()
    return redirect(url_for('home_app.home'))

web_app/views/cars.py
from flask import Blueprint, render_template, request, url_for, abort, flash
from flask_login import login_required, current_user
from injector import inject
from datetime import datetime
from services.VehicleAd import VehicleAdService
from forms.Car import CarAdForm
from decorators.admin import must_be_admin
import copy

cars_app = Blueprint('cars_app', __name__, template_folder='../templates')
vehicle_additional_relations = ['eco_standart', 'extras', 'car_body_configuration', 'gearbox', 'color']

@inject
@cars_app.route('/cars/new/', methods=['GET', 'POST'], endpoint='create')
@login_required
def create(vehicle_ad_service: VehicleAdService):
    
    if request.method == 'GET':
        return render_template('cars/create.html', current_year=datetime.utcnow().year)
    
    # POST request for car creation
    req_params = request.form
    form = CarAdForm(req_params)

    if form.validate():
        vehicle_ad_service.handle_ad_creation(req_params)
        return vehicle_ad_service.handle_successful_ad_creation()
    
    return vehicle_ad_service.handle_unsuccessful_ad_creation(req_params, form)
    

@cars_app.route('/cars/', methods=['GET'], endpoint='list_page')
def list_page():
    return render_template('cars/list.html')


@cars_app.route('/cars/my-ads', methods=['GET'], endpoint='list_my_ads')
@login_required
def list_my_ads():
    return render_template('cars/my-ads-list.html')


@cars_app.route('/cars/pending-approval', methods=['GET'], endpoint='list_pending_approval_ads')
@must_be_admin
def list_pending_approval_ads():
    return render_template('cars/pending-approval-ads.html')


@cars_app.route('/cars/data', methods=['GET'], endpoint='list_data')
def list_data(vehicle_ad_service: VehicleAdService):
    
    page = request.args.get(key='page', default=1, type=int)
    sort = request.args.get(key='sort', default='created_at_desc', type=str)

    if not vehicle_ad_service.is_valid_sort(sort):
        return {'message':'Invalid data'}, 400
    
    return vehicle_ad_service.paginated_extraction(page=page, per_page=12, filters={
        'make_id': request.args.get(key='make_id', default=0, type=int),
        'model_id': request.args.get(key='model_id', default=0, type=int),
        'region_id': request.args.get(key='region_id', default=0, type=int),
        'settlement_id': request.args.get(key='settlement_id', default=0, type=int),
        'max_price': request.args.get(key='max_price', default=0, type=float),
        'min_year': request.args.get(key='min_year', default=0, type=int),
        'fuel_type_id': request.args.get(key='fuel_type_id', default=0, type=int),
        'gearbox_id': request.args.get(key='gearbox_id', default=0, type=int),
        'publisher_id': request.args.get(key='publisher_id', default=0, type=int),
        'context': request.args.get(key='context', default='', type=str)
    }, sort=sort), 200



@cars_app.route('/cars/<int:id>', methods=['GET'], endpoint='detail')
def detail(id, vehicle_ad_service: VehicleAdService):
    
    vehicle_ad = vehicle_ad_service.get_by_id(id=id, relations=vehicle_additional_relations)
    
    if vehicle_ad is None:
        return abort(404)
    
    if not vehicle_ad.is_approved:
        if not current_user.is_authenticated:
            flash("Необходимо е да сте логнат за да видите неудобрената обява.", 'danger')
            return abort(403)

        if not (current_user.is_admin() or vehicle_ad.current_user_is_publisher):
            flash("Необходимо е да сте администратор или създателя на обявата за да разглеждате неудобрена обява.", 'danger')
            return abort(403)
        

    # Making clone and passing the clone into the template is used because if
    # any of the vehicle_ad properties are accessed after the update 
    # it will result in making SELECT requests for syncing object with the newest data.   
    vehicle_ad_copy = copy.deepcopy(vehicle_ad)
    vehicle_ad_service.increment_views(vehicle_ad)

    return render_template('cars/detail.html', vehicle_ad_obj=vehicle_ad_copy)


@inject
@cars_app.route('/cars/<id>/update', methods=['GET', 'POST'], endpoint='update')
def update(id, vehicle_ad_service: VehicleAdService):
    
    vehicle_ad = vehicle_ad_service.get_by_id(id=id, relations=vehicle_additional_relations)
    
    if vehicle_ad is None:
        return abort(404)

    if not vehicle_ad.current_user_is_publisher:
        flash('Само публикувалият потребител може да редактира собствената си обява.', 'danger')
        return abort(403)

    if request.method == 'GET':

        return render_template('cars/edit.html', 
            vehicle_serialization=vehicle_ad.serialize(relations=vehicle_additional_relations),
            car_edit_url=url_for('cars_app.update', id=vehicle_ad.id),
            current_year=datetime.utcnow().year
        )

    req_params = request.form
    form = CarAdForm(req_params)

    if form.validate():
        vehicle_ad_service.handle_ad_update(vehicle_ad=vehicle_ad, form_data=req_params)
        return vehicle_ad_service.handle_successful_ad_update()
    
    return vehicle_ad_service.handle_unsuccessful_ad_update(form)

@inject
@cars_app.route('/cars/<id>/delete', methods=['POST'], endpoint='delete')
def delete(id, vehicle_ad_service: VehicleAdService):
    
    vehicle_ad = vehicle_ad_service.get_by_id(id=id, relations=['extras', 'publisher'])
    
    if vehicle_ad is None:
        return abort(404)

    if not vehicle_ad.current_user_is_publisher:
        flash('Само публикувалият потребител може да изтрие собствената си обява.', 'danger')
        return abort(403)
    
    return vehicle_ad_service.handle_successful_ad_delete(vehicle_ad, True)

# Data is fetched by ajax and used for car search and create/edit form.
@inject
@cars_app.route('/cars/static-form-data', methods=['GET'], endpoint='static-data')
def car_forms_static_data(vehicle_ad_service: VehicleAdService):
    
    return vehicle_ad_service.get_static_form_data()

web_app/templates/layouts/app.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>{% block title %}{% endblock %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>
<body {% if body_id is defined %} id="{{body_id}}" {% endif %}>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler" aria-controls="navbar-toggler" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mt-2 mt-lg-0" id="navbar-toggler">
                <a class="navbar-brand" href="{{url_for('home_app.home')}}">Cars Market</a>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('home_app.home')}}">Начало</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('cars_app.create')}}">Публикуване</a>
                    </li>
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('cars_app.list_my_ads')}}">Мои Обяви</a>
                        </li>
                        {% if current_user.is_admin() %}
                            <li>
                                <a class="nav-link" href="{{url_for('cars_app.list_pending_approval_ads')}}">Обяви за одобрение</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('auth_app.logout')}}">Изход</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('auth_app.register')}}">Регистриране</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('auth_app.login')}}">Влизане</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% for category in ['primary', 'danger'] %}
        {% include 'partials/alert.html' %}
    {% endfor %}
    {% block content %}{% endblock %}
    <footer class="bg-light text-center text-lg-start">
        <p class="copyright mb-0 text-center">
            Cars Market © 2023
        </p>
    </footer>
    <script>
        {% block js_vars %}{% endblock %}
    </script>
    <script src="{{ asset_url('js/app.bundle.js') }}"></script>
</body>
</html>