web_app/forms/Car.py
from wtforms import Form, IntegerField, StringField, DecimalField
from wtforms.validators import DataRequired, Length, NumberRange, ValidationError
from datetime import date

from repositories.Model import ModelRepository
from repositories.FuelType import FuelTypeRepository
from repositories.EcoStandart import EcoStandartRepository
from repositories.Gearbox import GearboxRepository
from repositories.CarBodyConfiguration import CarBodyConfigurationRepository
from repositories.Color import ColorRepository
from repositories.Region import RegionRepository
from repositories.Settlement import SettlementRepository

from models.Make import MakeDBModel
from models.Model import ModelDBModel

import json


def validate_model(self, field):
    model = (ModelRepository()).get_by_id(id=field.data) 

    if model == None:
        raise ValidationError('Invalid model.')

    if model.make_id is not self.make_id.data:
        raise ValidationError('Model not matching make.')

def validate_fuel(self, field):
    if (FuelTypeRepository()).get_by_id(id=field.data) == None:
        raise ValidationError('Invalid fuel.')

def validate_eurostandart(self, field):
    if (EcoStandartRepository()).get_by_id(id=field.data) == None:
        raise ValidationError('Invalid eco standart.')

def validate_gearbox(self, field):
    if (GearboxRepository()).get_by_id(id=field.data) == None:
        raise ValidationError('Invalid gearbox.')

def validate_car_body_configuration(self, field):
    if (CarBodyConfigurationRepository()).get_by_id(id=field.data) == None:
        raise ValidationError('Invalid car body configuration.')

def validate_color(self, field):
    if (ColorRepository()).get_by_id(id=field.data) == None:
        raise ValidationError('Invalid color.')

def validate_region(self, field):
    if (RegionRepository()).get_by_id(id=field.data) == None:
        raise ValidationError('Invalid region.')

def validate_settlement(self, field):
    settlement = (SettlementRepository()).get_by_id(id=field.data)

    if settlement == None:
        raise ValidationError('Invalid settlement.')

    if settlement.region_id != self.region_id.data:
         raise ValidationError('Settlement does not match region.')

def validate_extras(self, field):
    
    extras = []
    
    try:
        extras = json.loads(field.data)
    except ValueError as e:
        raise ValidationError('Extras parameter is not a valid JSON.')
    
    if type(extras) is not list:
        raise ValidationError("Extras need to be array.")

    for extraID in extras:
        if type(extraID) is not int:
            raise ValidationError('Not all elements of the extras array are numeric.')

    # Don't validate here if the extras ids correspond to real record.
    # This is done in other service which sets records.

def validate_image_urls(self, field):
    
    image_urls = []
    
    try:
        image_urls = json.loads(field.data)
    except ValueError as e:
        raise ValidationError('Image urls parameter is not a valid JSON.')
    
    if type(image_urls) is not list:
        raise ValidationError('Image urls need to be array.')
    
    for image_url in image_urls:
        if type(image_url) is not str:
            raise ValidationError('Not all elements of the image urls array are numeric.')

        # Upload image size must be below 50 MB.
        if (len(image_url) * 3 / 4 - image_url.count('=', -2)) / (1024 * 1024) > 50 + 1: # +1 just to make sure size is not underestimated.
            raise ValidationError('Images above 50 MB are not allowed.')
        


class CarAdForm(Form):
    make_id = IntegerField(MakeDBModel, [DataRequired()])
    model_id = IntegerField(ModelDBModel, [DataRequired(), validate_model])
    modification = StringField('Modification', [DataRequired(), Length(min=3, max=20)])
    fuel_type_id = IntegerField('Fuel', [DataRequired(), validate_fuel])

    eco_standart_id = IntegerField('Eco Standart', [DataRequired(), validate_eurostandart])
    gearbox_id = IntegerField('Gearbox', [DataRequired(), validate_gearbox])
    car_body_configuration_id = IntegerField('Car Body Configuration', [DataRequired(), validate_car_body_configuration])
    color_id = IntegerField('Color', [DataRequired(), validate_color])

    price = DecimalField('Price', [DataRequired(), NumberRange(min=1, max=100_000_000)])
    hp = IntegerField('HP', [DataRequired(), NumberRange(min=1, max=10000)])
    manufacture_year = IntegerField('Manufacture Year', [DataRequired(), NumberRange(min=1900, max=date.today().year)])
    mileage = IntegerField('Mileage', [DataRequired(), NumberRange(min=0, max=50_000_000)])

    region_id = IntegerField('Region', [DataRequired(), validate_region])
    settlement_id = IntegerField('Settlement', [DataRequired(), validate_settlement])

    description = StringField('Description', [Length(max=500)])
    extras = StringField('Extras', [DataRequired(), Length(max=1000), validate_extras])

    image_urls = StringField('Image Urls', [DataRequired(), validate_image_urls])

web_app/views/admin.py
from flask import Blueprint, request, url_for, abort, redirect

from services.VehicleAd import VehicleAdService
from decorators.admin import must_be_admin


admin_app = Blueprint('admin_app', __name__, template_folder='../templates')

@admin_app.route('/admin/ads/<int:id>/approve', methods=['POST'], endpoint='approve_ad')
@must_be_admin
def approve_ad(id, vehicle_ad_service: VehicleAdService):
    vehicle_ad = vehicle_ad_service.get_by_id(id=id)
    
    if vehicle_ad is None:
        return abort(404)

    vehicle_ad_service.approve_ad(vehicle_ad)

    return redirect(url_for('cars_app.list_pending_approval_ads'))


@admin_app.route('/admin/ads/<int:id>/decline', methods=['POST'], endpoint='decline_ad')
@must_be_admin
def decline_ad(id, vehicle_ad_service: VehicleAdService):
    vehicle_ad = vehicle_ad_service.get_by_id(id=id)
    
    if vehicle_ad is None:
        return abort(404)

    vehicle_ad_service.decline_ad(vehicle_ad)

    return redirect(url_for('cars_app.list_pending_approval_ads'))

web_app/views/cars.py
from flask import Blueprint, render_template, request, url_for, abort, flash
from flask_login import login_required, current_user
from injector import inject
from datetime import datetime
from services.VehicleAd import VehicleAdService
from forms.Car import CarAdForm
from decorators.admin import must_be_admin
import copy

cars_app = Blueprint('cars_app', __name__, template_folder='../templates')
vehicle_additional_relations = ['eco_standart', 'extras', 'car_body_configuration', 'gearbox', 'color']

@inject
@cars_app.route('/cars/new/', methods=['GET', 'POST'], endpoint='create')
@login_required
def create(vehicle_ad_service: VehicleAdService):
    
    if request.method == 'GET':
        return render_template('cars/create.html', current_year=datetime.utcnow().year)
    
    # POST request for car creation
    req_params = request.form
    form = CarAdForm(req_params)

    if form.validate():
        vehicle_ad_service.handle_ad_creation(req_params)
        return vehicle_ad_service.handle_successful_ad_creation()
    
    return vehicle_ad_service.handle_unsuccessful_ad_creation(req_params, form)
    

@cars_app.route('/cars/', methods=['GET'], endpoint='list_page')
def list_page():
    return render_template('cars/list.html')


@cars_app.route('/cars/my-ads', methods=['GET'], endpoint='list_my_ads')
@login_required
def list_my_ads():
    return render_template('cars/my-ads-list.html')


@cars_app.route('/cars/pending-approval', methods=['GET'], endpoint='list_pending_approval_ads')
@must_be_admin
def list_pending_approval_ads():
    return render_template('cars/pending-approval-ads.html')


@cars_app.route('/cars/data', methods=['GET'], endpoint='list_data')
def list_data(vehicle_ad_service: VehicleAdService):
    
    page = request.args.get(key='page', default=1, type=int)
    sort = request.args.get(key='sort', default='created_at_desc', type=str)

    if not vehicle_ad_service.is_valid_sort(sort):
        return {'message':'Invalid data'}, 400
    
    return vehicle_ad_service.paginated_extraction(page=page, per_page=12, filters={
        'make_id': request.args.get(key='make_id', default=0, type=int),
        'model_id': request.args.get(key='model_id', default=0, type=int),
        'region_id': request.args.get(key='region_id', default=0, type=int),
        'settlement_id': request.args.get(key='settlement_id', default=0, type=int),
        'max_price': request.args.get(key='max_price', default=0, type=float),
        'min_year': request.args.get(key='min_year', default=0, type=int),
        'fuel_type_id': request.args.get(key='fuel_type_id', default=0, type=int),
        'gearbox_id': request.args.get(key='gearbox_id', default=0, type=int),
        'publisher_id': request.args.get(key='publisher_id', default=0, type=int),
        'context': request.args.get(key='context', default='', type=str)
    }, sort=sort), 200



@cars_app.route('/cars/<int:id>', methods=['GET'], endpoint='detail')
def detail(id, vehicle_ad_service: VehicleAdService):
    
    vehicle_ad = vehicle_ad_service.get_by_id(id=id, relations=vehicle_additional_relations)
    
    if vehicle_ad is None:
        return abort(404)
    
    if not vehicle_ad.is_approved:
        if not current_user.is_authenticated:
            flash("Необходимо е да сте логнат за да видите неудобрената обява.", 'danger')
            return abort(403)

        if not (current_user.is_admin() or vehicle_ad.current_user_is_publisher):
            flash("Необходимо е да сте администратор или създателя на обявата за да разглеждате неудобрена обява.", 'danger')
            return abort(403)
        

    # Making clone and passing the clone into the template is used because if
    # any of the vehicle_ad properties are accessed after the update 
    # it will result in making SELECT requests for syncing object with the newest data.   
    vehicle_ad_copy = copy.deepcopy(vehicle_ad)
    vehicle_ad_service.increment_views(vehicle_ad)

    return render_template('cars/detail.html', vehicle_ad_obj=vehicle_ad_copy)


@inject
@cars_app.route('/cars/<id>/update', methods=['GET', 'POST'], endpoint='update')
def update(id, vehicle_ad_service: VehicleAdService):
    
    vehicle_ad = vehicle_ad_service.get_by_id(id=id, relations=vehicle_additional_relations)
    
    if vehicle_ad is None:
        return abort(404)

    if not vehicle_ad.current_user_is_publisher:
        flash('Само публикувалият потребител може да редактира собствената си обява.', 'danger')
        return abort(403)

    if request.method == 'GET':

        return render_template('cars/edit.html', 
            vehicle_serialization=vehicle_ad.serialize(relations=vehicle_additional_relations),
            car_edit_url=url_for('cars_app.update', id=vehicle_ad.id),
            current_year=datetime.utcnow().year
        )

    req_params = request.form
    form = CarAdForm(req_params)

    if form.validate():
        vehicle_ad_service.handle_ad_update(vehicle_ad=vehicle_ad, form_data=req_params)
        return vehicle_ad_service.handle_successful_ad_update()
    
    return vehicle_ad_service.handle_unsuccessful_ad_update(form)

@inject
@cars_app.route('/cars/<id>/delete', methods=['POST'], endpoint='delete')
def delete(id, vehicle_ad_service: VehicleAdService):
    
    vehicle_ad = vehicle_ad_service.get_by_id(id=id, relations=['extras', 'publisher'])
    
    if vehicle_ad is None:
        return abort(404)

    if not vehicle_ad.current_user_is_publisher:
        flash('Само публикувалият потребител може да изтрие собствената си обява.', 'danger')
        return abort(403)
    
    return vehicle_ad_service.handle_successful_ad_delete(vehicle_ad, True)

# Data is fetched by ajax and used for car search and create/edit form.
@inject
@cars_app.route('/cars/static-form-data', methods=['GET'], endpoint='static-data')
def car_forms_static_data(vehicle_ad_service: VehicleAdService):
    
    return vehicle_ad_service.get_static_form_data()

web_app/templates/cars/create.html
{% set body_id = 'car-ad-creation' %}
{% extends 'layouts/app.html' %}

{% block title %}
    Създаване на обява
{% endblock %}

{% block content %}
    <h1 class="h3 text-center mt-4 mb-3">Създаване на обява</h1>
    <div id="car-ad-form" class="container"></div>
{% endblock %}

{% block js_vars %}
    var fromPython = {
        staticFormDataUrl: "{{url_for('cars_app.static-data')}}",
        carCreationUrl: "{{ url_for('cars_app.create') }}",
        currentYear: {{current_year}},
    }
{% endblock %}

web_app/templates/cars/detail.html
{% set body_id = 'car-ad-details' %}
{% extends 'layouts/app.html' %}

{% block title %}
    Обява
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="d-flex justify-content-between">
            <div>
                {# + 1 since passed vehicle object does not contain the incremented views value. #}
                <p class="mb-3">Разглеждания: {{vehicle_ad_obj.views + 1}}</p>
            </div>
            <div class="offer-price-badge ms-auto">
                <span>{{vehicle_ad_obj.format_price}} лв.</span>
            </div>
        </div>

        <div class="mb-4">
            <h1 class="h2 mt-3">{{vehicle_ad_obj.make.title}} {{vehicle_ad_obj.model.title}} {{vehicle_ad_obj.modification}} {{vehicle_ad_obj.gearbox.title}}</h1>
            <p>
                {{vehicle_ad_obj.manufacture_year}} година, {{vehicle_ad_obj.fuel_type.title}}, {{vehicle_ad_obj.car_body_configuration.title}}, {{vehicle_ad_obj.mileage}} км, {{vehicle_ad_obj.gearbox.title}} скорост, {{vehicle_ad_obj.hp}} к.с., {{vehicle_ad_obj.eco_standart.title}}, {{vehicle_ad_obj.color.title}}
            </p>
        </div>

        <div class="row">
            <div class="col-12 col-md-5">
                <h3 class="h5 mb-4">Описание:</h3>
                <p>{{vehicle_ad_obj.description}}</p>
                <hr>

                <h3 class="h5 mb-4">Особености и екстри:</h3>
                {% for extra_category_title, exras_str in vehicle_ad_obj.extra_categories_data.items() %}
                    <p>
                        <strong>{{ extra_category_title }}</strong>: {{ exras_str }}
                    </p>
                {% endfor %}
                <hr>
                <a class="btn btn-primary mb-2" href="tel:{{vehicle_ad_obj.publisher.phone}}">
                    <span class="text-white d-inline-block me-1"
                        style="width: 17px; position: relative; top: -2px; fill: white;">
                        {% with icon='phone-solid' %}
                            {% include 'partials/icons.html' %}
                        {% endwith %}
                    </span>
                    <span>{{vehicle_ad_obj.publisher.phone}}</span>
                </a>
                <p class="mb-1">Продавач: {{vehicle_ad_obj.publisher.first_name}}</p>
                <b class="d-block mb-3">{{vehicle_ad_obj.settlement.title}}, област: {{vehicle_ad_obj.settlement.region.title}}</b>
                
                {% if current_user.is_authenticated and current_user.is_admin() %}
                    <div class="admin-actions-container"></div>
                {% endif %}
            </div>
            <div class="col-12 col-md-7">
                <div id="car-thumbnail-slider" class="mb-3"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_vars %}
    var fromPython = {
        imagesUrls: {{vehicle_ad_obj.images_urls|tojson}},
        vehicleStatus: "{{vehicle_ad_obj.status}}",
        acceptUrl: "{{url_for('admin_app.approve_ad', id=vehicle_ad_obj.id)}}",
        declinetUrl: "{{url_for('admin_app.decline_ad', id=vehicle_ad_obj.id)}}"
    }
{% endblock %}

web_app/templates/cars/edit.html
{% set body_id = 'car-ad-edit' %}
{% extends 'layouts/app.html' %}

{% block title %}
    Редактиране на обява
{% endblock %}

{% block content %}
    <h1 class="h3 text-center mt-4 mb-3">Редактиране на обява</h1>
    <div id="car-ad-form" class="container"></div>
{% endblock %}

{% block js_vars %}
    var fromPython = {
        staticFormDataUrl: "{{url_for('cars_app.static-data')}}",
        vehicleId: {{vehicle_serialization['id']}},
        carEditUrl: "{{car_edit_url}}",
        vehicleParams: {{vehicle_serialization|tojson}},
        currentYear: {{current_year}},
    }
{% endblock %}

web_app/templates/cars/list.html
{% set body_id = 'car-list' %}
{% extends 'layouts/app.html' %}

{% block title %}
    Списък с обяви
{% endblock %}

{% block content %}
<div class="container mb-3">
    <p class="h2 mt-5 mb-4 text-center">Списък с обяви</p>
    <div id="car-ads-listing"></div>
</div>
{% endblock %}

{% block js_vars %}
    var fromPython = {
        vehicleListDataUrl: "{{request.url_root[:-1] + url_for('cars_app.list_data')}}"
    }
{% endblock %}

web_app/templates/cars/my-ads-list.html
{% set body_id = 'my-ads-list' %}
{% extends 'layouts/app.html' %}

{% block title %}
    Мои Обяви
{% endblock %}

{% block content %}
<div class="container mb-3">
    <p class="h2 mt-5 mb-4 text-center">Списък с мои обяви</p>
    <div id="my-ads-listing"></div>
</div>
{% endblock %}

{% block js_vars %}
    var fromPython = {
        vehicleListDataUrl: "{{request.url_root[:-1] + url_for('cars_app.list_data')}}",
        userID: {{current_user.id}}
    }
{% endblock %}

web_app/templates/cars/pending-approval-ads.html
{% set body_id = 'pending-approval-ads' %}
{% extends 'layouts/app.html' %}

{% block title %}
    Обяви, изчакващи одобрение 
{% endblock %}

{% block content %}
<div class="container mb-3">
    <p class="h2 mt-5 mb-4 text-center">Обяви за одобрение </p>
    <div id="pending-approval-ads-list"></div>
</div>
{% endblock %}

{% block js_vars %}
    var fromPython = {
        vehicleListDataUrl: "{{request.url_root[:-1] + url_for('cars_app.list_data')}}"
    }
{% endblock %}